import React, { useMemo, useState } from 'react'
import { Activity, ArrowUpRight, Bell, CalendarDays, CheckCircle2, ChevronRight, CirclePlus, Clock3, ExternalLink, Filter, Mail, Plus, RefreshCw, Sparkles, Target, TrendingUp, UserRound, UsersRound } from 'lucide-react'
import { CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './analytics.css'

const stageColors = { New: '#efb464', Contacted: '#60a5a0', Converted: '#e27d60' }
const formatDate = (value) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(value))
const relativeTime = (value) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago` }

export default function AnalyticsEnhanced({ leads, onCreate, onNavigate, onSelect, onPublicSite }) {
  const [range, setRange] = useState(7)
  const now = new Date('2026-09-06T23:59:59')
  const start = new Date(now); start.setDate(now.getDate() - range + 1); start.setHours(0, 0, 0, 0)
  const rangeLeads = useMemo(() => leads.filter((lead) => new Date(lead.createdAt) >= start && new Date(lead.createdAt) <= now), [leads, range])
  const total = rangeLeads.length
  const newLeads = rangeLeads.filter((lead) => lead.status === 'New').length
  const contacted = rangeLeads.filter((lead) => lead.status === 'Contacted').length
  const converted = rangeLeads.filter((lead) => lead.status === 'Converted').length
  const conversionRate = total ? Math.round(converted / total * 100) : 0
  const contactedRate = total ? Math.round(contacted / total * 100) : 0
  const followUps = leads.filter((lead) => lead.followUpDate)
  const today = new Date('2026-09-06T00:00:00')
  const upcoming = followUps.filter((lead) => new Date(`${lead.followUpDate}T00:00:00`) >= today).length
  const overdue = followUps.filter((lead) => new Date(`${lead.followUpDate}T00:00:00`) < today).length
  const activities = useMemo(() => leads.flatMap((lead) => [
    { id: `${lead.id}-created`, date: lead.createdAt, icon: CirclePlus, text: 'New inquiry received', lead: lead.name },
    ...(lead.status !== 'New' ? [{ id: `${lead.id}-status`, date: lead.createdAt, icon: Activity, text: lead.status === 'Converted' ? 'Lead converted' : 'Lead contacted', lead: lead.name }] : []),
    ...(lead.followUpDate ? [{ id: `${lead.id}-followup`, date: `${lead.followUpDate}T09:00:00`, icon: CalendarDays, text: 'Follow-up scheduled', lead: lead.name }] : []),
    ...(lead.notes || []).map((note) => ({ id: note.id, date: note.createdAt, icon: Mail, text: 'Note added', lead: lead.name }))
  ]).sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 5), [leads])
  const chartData = useMemo(() => Array.from({ length: range }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); const key = date.toISOString().slice(0, 10); return { date: formatDate(date), count: rangeLeads.filter((lead) => lead.createdAt.slice(0, 10) === key).length } }), [range, rangeLeads])
  const peak = chartData.reduce((current, item) => item.count > current.count ? item : current, { count: 0, date: 'No peak yet' })
  const average = range ? (total / range).toFixed(1) : '0.0'
  const distribution = ['New', 'Contacted', 'Converted'].map((name) => ({ name, value: rangeLeads.filter((lead) => lead.status === name).length }))
  const insightText = total ? [`${conversionRate}% of inquiries have converted.`, `${contactedRate}% of inquiries have reached the contacted stage.`, `${newLeads} lead${newLeads === 1 ? '' : 's'} currently waiting for first contact.`, `${converted} client${converted === 1 ? '' : 's'} successfully converted.`] : ['No inquiries were created in this period.', 'Try expanding the date range to see pipeline insights.']
  const kpis = [{ label: 'Total inquiries', value: total, supporting: `${range}-day intake volume`, icon: UsersRound }, { label: 'New leads', value: newLeads, supporting: 'Currently in intake', icon: CirclePlus }, { label: 'Contacted', value: contacted, supporting: `${contactedRate}% of total`, icon: Activity }, { label: 'Converted', value: converted, supporting: `${conversionRate}% conversion`, icon: Target }]
  return <div className="page analytics-page">
    <div className="page-heading analytics-heading"><div><p className="eyebrow">PERFORMANCE OVERVIEW</p><h1>Good morning, Demo Admin <span>👋</span></h1><p className="muted">Here's what's happening across your client pipeline.</p></div><label className="range-select"><CalendarDays size={16} /><select value={range} onChange={(event) => setRange(Number(event.target.value))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label></div>
    <div className="analytics-kpis">{kpis.map(({ label, value, supporting, icon: Icon }) => <div className="analytics-kpi" key={label}><div className="kpi-icon"><Icon size={17} /></div><div><span>{label}</span><strong>{value}</strong><small><ArrowUpRight size={12} /> {supporting}</small></div></div>)}</div>
    <section className="funnel-panel premium-funnel"><div className="panel-heading"><div><p className="eyebrow">PIPELINE CONVERSION FUNNEL</p><h2>Track the client journey</h2><p className="muted">Track how inquiries progress from first contact to converted client.</p></div><TrendingUp size={20} className="heading-icon" /></div><div className="connected-funnel">{[['01', 'INTAKE', 'Total inquiries', total, 100], ['02', 'SCOPING', 'Contacted leads', contacted, contactedRate], ['03', 'RETAINED', 'Converted clients', converted, conversionRate]].map(([number, title, label, value, percent], index) => <div className="connected-stage" key={title}><div className="stage-number">{number}</div><div className="stage-copy"><strong>{title}</strong><span>{label}</span></div><div className="stage-value"><b>{value}</b><small>{percent}% of intake</small></div><div className="stage-visual"><div style={{ width: `${Math.max(percent, value ? 8 : 2)}%` }} /></div>{index < 2 && <ChevronRight className="stage-arrow" size={17} />}</div>)}</div><div className="funnel-insight"><Sparkles size={15} /> Your current conversion rate is <strong>{conversionRate}%</strong>.</div></section>
    <div className="analytics-grid enhanced-grid"><section className="panel chart-panel"><div className="panel-heading compact"><div><p className="eyebrow">INTAKE VELOCITY</p><h2>Incoming leads over time</h2><p className="muted">Incoming leads over recent days.</p></div><div className="chart-summary"><span>AVERAGE DAILY INQUIRIES</span><strong>{average}</strong><small>Peak: {peak.date}</small></div></div><ResponsiveContainer width="100%" height={245}><LineChart data={chartData} margin={{ top: 12, right: 12, bottom: 0, left: -24 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8e9e4" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: '#8b918a', fontSize: 11 }} minTickGap={22} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#8b918a', fontSize: 12 }} /><Tooltip contentStyle={{ border: '1px solid #e3e6df', borderRadius: 7, fontSize: 12 }} /><Line type="monotone" dataKey="count" name="Inquiries" stroke="#e27d60" strokeWidth={3} dot={{ fill: '#fff', stroke: '#e27d60', strokeWidth: 2, r: 4 }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></section><section className="panel chart-panel"><div className="panel-heading compact"><div><p className="eyebrow">STAGE DISTRIBUTION</p><h2>Current lead mix</h2><p className="muted">Real-time volume by stage.</p></div></div><div className="donut-wrap enhanced-donut"><div className="donut-chart"><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={distribution} innerRadius={57} outerRadius={78} paddingAngle={4} dataKey="value">{distribution.map((entry) => <Cell key={entry.name} fill={stageColors[entry.name]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{total}</strong><span>Total leads</span></div></div><div className="legend-list">{distribution.map((item) => <div key={item.name}><span style={{ background: stageColors[item.name] }} /><p>{item.name}<strong>{item.value}<small>{total ? Math.round(item.value / total * 100) : 0}%</small></strong></p></div>)}</div></div></section></div>
    <div className="insight-grid"><section className="panel insight-panel"><div className="panel-heading compact"><div><p className="eyebrow">CONVERSION INSIGHTS</p><h2>What the numbers say</h2></div><Sparkles size={18} className="heading-icon" /></div>{insightText.map((text, index) => <div className="insight-row" key={text}><span>{index + 1}</span><p>{text}</p></div>)}</section><section className="panel followup-overview"><div className="panel-heading compact"><div><p className="eyebrow">FOLLOW-UP OVERVIEW</p><h2>Keep momentum going</h2></div><Clock3 size={18} className="heading-icon" /></div><div className="followup-stats"><button onClick={() => onNavigate('dashboard', 'upcoming')}><strong>{upcoming}</strong><span>Upcoming</span></button><button onClick={() => onNavigate('dashboard', 'overdue')}><strong>{overdue}</strong><span>Overdue</span></button><button onClick={() => onNavigate('dashboard', 'completed')}><strong>0</strong><span>Completed</span></button></div><p className="muted">Select a category to view matching pipeline leads.</p></section></div>
    <div className="activity-actions-grid"><section className="panel activity-panel"><div className="panel-heading compact"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest CRM activity</h2></div><Bell size={18} className="heading-icon" /></div>{activities.length ? activities.map(({ id, icon: Icon, text, lead, date }) => <button className="activity-row" key={id} onClick={() => onSelect(leads.find((item) => item.name === lead))}><span className="activity-icon"><Icon size={14} /></span><span><strong>{text}</strong><small>{lead}</small></span><time>{relativeTime(date)}</time></button>) : <div className="small-empty">No activity recorded yet.</div>}</section><section className="panel quick-actions"><div className="panel-heading compact"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Move work forward</h2></div><ArrowUpRight size={18} className="heading-icon" /></div><button onClick={onCreate}><Plus size={16} /> Add lead</button><button onClick={() => onNavigate('dashboard')}><UsersRound size={16} /> View pipeline</button><button onClick={() => onNavigate('dashboard', 'schedule')}><CalendarDays size={16} /> Schedule follow-up</button><button onClick={onPublicSite}><ExternalLink size={16} /> View public site</button></section></div>
  </div>
}
